### ISSUE TITLE
Social preview image

### ISSUE THREAD

**Issue by crazko** [slovensko-help/slovensko-help#1]
Pre repozitár sa dá [nastaviť Preview image](https://help.github.com/en/github/administering-a-repository/customizing-your-repositorys-social-media-preview), ktorý funguje ako open graph image. Pri zdieľaní webu na sociálnych sieťach sa momentálne zobrazuje foto autora (posledného commitu). Mohlo by sa nastaviť niečo viac reprezentatívne.

Pridávam rýchly nástrel, ktorý má potrebné rozmery a dá sa teda rovno použiť:

![slovensko-help-github](https://user-images.githubusercontent.com/1255989/77001956-0aa8da80-695b-11ea-8552-edaaba636851.png)

Otestovať web sa dá napr. tu: https://metatags.io/

**Comment by misotrnka** [comment]
Super point, zmenil som to. Vďaka.
